name: Update AWS Lambda Function

on:
  push:
    branches:
      - main

jobs:
  update_lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package code
      run: zip -r function.zip . -x "*.git*"

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name CWB-API-radar \
          --zip-file fileb://function.zip \
          --publish
